### ISSUE TITLE
Noob - I have no clue D:

### ISSUE THREAD

**Issue by ShiaTheMLGPro** [rastapasta/pokemon-go-mitm#143]
Hello all, I'm interested in this project and want to change a single pokemon's model to a Legendary for the cosmetic value but I'm afraid I have no clue how to go about setting this up.

If anyone is willing to help me via Skype, that would be amazing.
I'm not banking on any help but I'll still ask for it.

Kind Regards
Shia

**Comment by jmoriau** [comment]
Issues are not a support forum. Please look at the examples what you want exists already and close this.

**Comment by ShiaTheMLGPro** [comment]
I knew that someone would comment something as unhelpful as that.
An issue is something that a person cannot solve, therefore I have posted it in the issue tab to ask for help... I have looked at the "examples" yet I can't seem to figure it out, in the future, please post helpful things as opposed to your sour comments.

Cheers
Shia

**Comment by jmoriau** [comment]
An issue is a real issue with the project not with your failure to read the instruction or the examples.

**Comment by ShiaTheMLGPro** [comment]
I can link you several issues that are cries for help if you would like, mate.

Here's some more helpful information regarding my issue, that I have posted in the ISSUES section ...

I have Node JS, it's just a cmd window, I have the example code I wish to use, how does one generate the MITM Certificate?

I don't want replied from peasants such as yourself, jmoriau.

Thanks
Shia

**Comment by jmoriau** [comment]
Ugh you just proved my point you didn't even read the README, or you would have your answer already.
Again the ISSUES are for issues with the project not your setup. Again it's not a support forum.

And yes, since pokemongo was released, everyone makes a github account to come "cry for help" as you say.
Doesn't mean it's okay. Most of the other big pokemon projects have disabled the issues for this very reason or at least limited it to contributors only. Because non-programmers like yourself think it's the right place to be spoon-fed everything, just look at all the closed issues asking for a "youtube video tutorial".

Finally if you can't understand that what you're trying to achieve is already available in the examples you shouldn't use this project. This project is not meant to be one-click install/run by non-programmers. It's meant instead to be used as building-blocks to write yourself what you want to achieve. If you can't write (or don't even know what is) coffeescript/javascript you really can't use this.

**Comment by ShiaTheMLGPro** [comment]
Yes, I did read the README, it's normally the first thing you look at when it comes to anything and everything.
I'm terribly sorry that I can't read coffee script/java script and I'm even more sorry that you don't possess the capability to even offer a single iota of help. I have provided several steps that I have taken to attempt to get this to work and you persist to shit on me, for not trying hard enough?

What a lovely first impression you have made for this community.

Get cancer and Kind Regards
Shia
