### ISSUE TITLE
Which file do I edit so I could evolve any Pokemon into Mew?

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#156]
Which file do I edit so I could evolve any Pokemon into Mew?
Just for a visual that it will look like I have evolved him into a mew

**Comment by jmoriau** [comment]
Hello,

Again issues are not a support forum. This project is not meant to be used as-is it's meant provide you with the building blocks to write yourself your own scripts. If you can't write basic javascript / coffeescript then I'm afraid you can't use it.

Also please stop making an issue every 10 minutes because you can't read a README.
