### ISSUE TITLE
Question. Is it possible to use with nox or bluestacks

### ISSUE THREAD

**Issue by Atrion** [rastapasta/pokemon-go-mitm#161]
I title stated can this be made to work with nox or bluestacks? If so is there any instructions how to do so? Sorry if this not where to ask.

**Comment by jmoriau** [comment]
- just install nox as you usually do
- drop the apk (if you have a pre-patched apk to bypass certificate pinning you can skip the next 2 steps)
- install the Xposed installer 
- install the xposed module to bypass the certificate pinning
- reboot
- set the proxy in the settings or using ProxyDroid
- run the app

But I wouldn't run nox/any emulator anymore, since they started checking unknown6 they use your device info as one of the components of the signature, I have no idea if they are able to extract back the informations when they get the request but if they do they'll clearly be able to see that you're running it on nox :/

here are all the fields they use from your device:
```         device_id:
            android_board_name:
            android_bootloader: 
            device_brand: 
            device_model: 
            device_model_identifier: 
            device_model_boot: 
            hardware_manufacturer: 
            hardware_model: 
            firmware_brand: 
            firmware_tags: 
            firmware_type: 
            firmware_fingerprint: ```

**Comment by trisk** [comment]
Yes, the server verifies the signature blob by decrypting it so they can see all of the data in it. I think this can be closed since there's no specific instructions necessary.

**Comment by toolsforpc** [comment]
Yes, definitely you could do it, BlueStacks in my opinion is much better option, just have a better research. Follow this link for more info about how to run apps and games on your PC  -http://toolsforpc.com
