### ISSUE TITLE
Question. Displaying a message on the device.

### ISSUE THREAD

**Issue by jaosha** [rastapasta/pokemon-go-mitm#162]
How would I go about displaying a string or a message in game on the device containing data from the mitm proxy on my computer? Is there a built-in method or function in Pokemon Go already that I can utilize? If not, how would I go about doing so? I was maybe thinking about displaying the capture_probability for all the types of pokeballs on the device whenever I encounter a pokemon just so that I am aware of the odds that I am dealing with. Or maybe even possibly displaying the CatchPokemon status the moment the pokeball hits the pokemon so you know right away whether or not you caught the pokemon or if it has escaped or fled. Any help at all would be absolutely great! Thanks in advanced!

**Comment by jmoriau** [comment]
Uh that would be nice indeed, but the only thing you can do is modify an incoming response to trick the client to replace a string with another one (like the display_iv example it modify the response to append the IV% at the end of each pokemon's nickname).

You cannot yourself add any UI elements to the app. I don't remember how often the inventory is refreshed (haven't used the app since they started to check unknown6) but what you could do is once you're in an encounter save the probabilities in a global, and then append the probability of each pokeball to their name in the inventory when the inventory response comes in.

That way when you're in an encounter you would just have to wait for the inventory to be refreshed and when you check your bag you could see the probability of each pokeball in their name.

Maybe. I haven't tried, but that's how I would approach it.

**Comment by rastapasta** [comment]
Think about something like https://pushover.net/ - you install the app on your mobile and add the api call to their service into the MITM script. This would make it pretty easy to enable solid push notifications like IV of just caught pokemon. Cheers!

**Comment by rastapasta** [comment]
other idea:
* use the username as temporary display after a catch! (it gets pulled after a catch to get the new stardust -> intercept!)
* use the nickname append like in the display_iv

it's not as cool as prompting a user a message box with an own string though :)

**Comment by jaosha** [comment]
Your first idea was what I was exactly just thinking about! I was thinking about maybe a separate app that will either send push notifications to the phone or maybe an overlay that would display data. Never knew there was already a service for what I was looking for haha. I just have no idea how to actually add the api to the MITM script and actually configure it to my liking since I'm not quite familiar with the CoffeeScript/JavaScript language. If anyone is willing to guide me a bit then that would be greatly appreciated! :) I'm just wondering how difficult it'd be actually code my own app for this on my android device. The overlayed message won't be the biggest problem for me, but how to actually send data from the MITM script to the app. Sorry if any of this is too much too ask for! But thanks yet again in advance!
