### ISSUE TITLE
Why coffee script ?

### ISSUE THREAD

**Issue by LeaklessGfy** [rastapasta/pokemon-go-mitm#64]
This is a pretty simple question but while you need node to install dependencies why make it in coffee whereas you could do this with pure js/node ?

Is there a specific reason or it just a question of taste ?

Thanks !

**Comment by rastapasta** [comment]
Question of taste :) Coffee makes my code cleaner and much more readable since years - in my work and fun. Less noise by parenthesizes and replacing their need by readability-enhancing indentation. Functional coding patterns. An extendable JS 'class' pattern. And so on :-)

You won't need to use CoffeeScript yourself though to use the lib.
Cheers and happy coffee scripting! :)

Recommended reads: https://coffeescript-cookbook.github.io/

**Comment by trisk** [comment]
This is my first time writing CoffeeScript, and I appreciate how easy it was to pick up the compact (somewhat Pythonic) syntax which has made things like list comprehensions extremely painless to both read and write.
